<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "rlkickstart"
 *
 * Auto generated by Extension Builder 2017-11-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Resterland Kickstart',
    'description' => 'Setting up a basic page tree for starting new web projects',
    'category' => 'distribution',
    'author' => 'Roland Fuhrer',
    'author_email' => 'roland@resterland.ch',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '8.7.8',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.99.99',
            'realurl' => '',
            'scheduler' => '',
            'linkvalidator' => '',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
